genere/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path("",views.index.as_view(),name="index"),

   path('<pk>/',views.details.as_view(),name="details"),


]

p1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('genere/',include('genere.urls')),

]

genere/models.py
from django.db import models

# Create your models here.
class Collection(models.Model):
    collection_name = models.CharField(max_length=100)
    discription = models.CharField(max_length=100)
    collcover = models.CharField(max_length=1000)
    def __str__(self):
        return self.collection_name

class Piece(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    type =models.CharField(max_length=100)
    year =models.IntegerField()
    artist =models.CharField(max_length=100)
    piececover =models.CharField(max_length=1000)
    def __str__(self):
        return self.title

genere/views.py
from django.http import HttpResponse
from .models import Collection,Piece
from django.views import generic

# Create your views here.
class index(generic.ListView):
    template_name ="genere\\generetemplates.html"
    def get_queryset(self):
        return Collection.objects.all

class details(generic.DeleteView):
   model = Collection
   template_name = "genere\\detailstemplates.html"

genere/templates/genere/detailstemplates.html
<!DOCTYPE html>
<html>
<head>
<title>Piece</title>
</head>
<body>
    {% for item in collection.piece_set.all %}
       
    <div align="center">
    <img src="{{item.piececover}}" height="200" width="200">
    <h2>{{item.title}}-{{item.artist}}</h2>
    <h3>{{item.year}}</h3>
       
    </br>
</div>
    {% endfor %}

</body>
</html>

genere/templates/genere/generetemplates.html
<!DOCTYPE html>
<html>
<head>
<title>genere</title>
</head>
<body>
    <h1>Html page</h1>
    {% for item in object_list %}
       
    <div align="center">
    <img src="{{item.collcover}}" height="200" width="200">
    <h2><a href="/genere/{{item.pk}}">{{item.collection_name}}</a></h2>
    <h3>{{item.description}}</h3>
       
    </br>
</div>
    {% endfor %}

</body>
</html>